server:
  port: 8080
spring:
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: qaz123!@#  
  jackson:    date-format: yyyy-MM-dd HH:mm:ss    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:com/xw/poseidon/dao/impl/*.xml      
logging:
  config: classpath:logback-dev.xml
